---
## This is a defaults file, it's likely to be changed during repo updates
## To override, or update settings, or configuration, create a new file
## in this directory, e.g. "overrides.yml" which will take precedence.
radosgw_address_block: "{{ public_network }}"
radosgw_civetweb_bind_ip:
   "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] | ipaddr(radosgw_address_block) | first }}"
internal_lb_vip_address: "127.0.0.1"
keystone_service_adminurl: "http://{{ internal_lb_vip_address }}:35357"
## RadosGW Integration vars
## These need to be removed if not integrating with OpenStack
## NB The radosgw_keystone vars exist for backwards compat with ceph-ansible v2.x
radosgw_keystone_service_name: "cephRGW"
radosgw_keystone_service_type: "object-store"
radosgw_keystone_service_description: "Ceph RADOS Gateway Service"
radosgw_keystone_service_region: "{{ service_region }}"
radosgw_keystone_admin_user: radosgw
radosgw_keystone_admin_tenant: service
## Use this to override existing RGW specific config template settings,
## whilst keeping the defaults.
ceph_conf_overrides_rgw_extra: {}
ceph_conf_overrides_rgw:
   "{{ (radosgw_keystone | bool)
          | ternary(ceph_conf_overrides_rgw_keystone, ceph_conf_overrides_rgw_default)
          | combine(ceph_conf_overrides_rgw_extra, recursive = True) }}"
ceph_conf_overrides_rgw_default:
  client:
    rgw_cache_lru_size: 250000
    rgw_thread_pool_size: 8192
    rgw_num_rados_handles: 8
ceph_conf_overrides_rgw_keystone:
  client:
    rgw_cache_lru_size: 250000
    rgw_thread_pool_size: 8192
    rgw_num_rados_handles: 8
  "client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}":
    # OpenStack integration with Keystone
    rgw_keystone_url: "{{ keystone_service_adminurl }}"
    rgw_keystone_api_version: 3
    rgw_keystone_admin_user: "{{ radosgw_keystone_admin_user }}"
    rgw_keystone_admin_password: "{{ radosgw_keystone_admin_password }}"
    rgw_keystone_admin_tenant: "{{ radosgw_keystone_admin_tenant }}"
    rgw_keystone_admin_domain: default
    rgw_keystone_accepted_roles: 'Member, _member_, admin'
    rgw_s3_auth_use_keystone: true
    rgw_swift_account_in_url: true
    rgw_keystone_implicit_tenants: true
